import { Directive, ElementRef } from '@angular/core';
import { NgControl, FormGroup, FormArray } from '@angular/forms';
import { IResPlan,IProject } from 'app/resourcePlans/res-plan.model';

@Directive({
  selector: '[showHideAutoGeneratedText]'
})
export class ShowHideAutoGeneratedTextDirective {

  constructor(private el: ElementRef,private control : NgControl) { 
    let resPlan:IResPlan = this.control.value as IResPlan;
    let projectControls = this.control["projects"] as FormArray;
    projectControls.controls.forEach(projectControl => {
      // if project is auto generated hceck if any children interval cell dirty
      if((projectControl.value as IProject).autoGenerated)
      {
       let intervalCellControls = (projectControl as FormGroup).controls["intervals"] as FormArray;
       if(intervalCellControls.controls.find(c=>c.dirty == true)){
        this.control.control.setValue("HasAutoGeneratedProjects",true);
       }
      }
    });
  }

}
