import { ShowHideAutoGeneratedTextDirective } from './show-hide-auto-generated-text.directive';

describe('ShowHideAutoGeneratedTextDirective', () => {
  it('should create an instance', () => {
    const directive = new ShowHideAutoGeneratedTextDirective();
    expect(directive).toBeTruthy();
  });
});
